CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS teams (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    team_type VARCHAR(50) NOT NULL CHECK (team_type IN ('SOCCER', 'BASKETBALL', 'BASEBALL')),
    league VARCHAR(100) NOT NULL,
    season VARCHAR(20) NOT NULL
    
);
